// apps/react-app/src/components/Components.tsx
import { TkCard } from '@takeoff-ui/react';
import { Link } from 'react-router-dom';

function Components() {
  return (
    <TkCard>
      <div slot="header">
        <h1 className="p-3 text-3xl font-semibold text-slate-500">Components</h1>
      </div>

      <p>Komponent testleri için aşağıdan komponent seçebilirsiniz. Burada olmayan komponentleri benzer düzende ekleyebilirsiniz.</p>

      <div className="grid grid-cols-6 gap-4 mt-4">
        <Link to="input" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Input
        </Link>

        <Link to="stepper" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Stepper
        </Link>

        <Link to="toggle" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Toggle
        </Link>

        <Link to="divider" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Divider
        </Link>

        <Link to="pagination" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Pagination
        </Link>

        <Link to="editor" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Editor
        </Link>

        <Link to="drawer" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Drawer
        </Link>

        <Link to="timeline" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Timeline
        </Link>

        <Link to="spinner" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Spinner
        </Link>

        <Link to="icon" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Icon
        </Link>

        <Link to="chips" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Chips
        </Link>
        <Link to="textarea" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Textarea
        </Link>
        <Link to="chart" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Chart
        </Link>
        <Link to="card" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Card
        </Link>
        <Link to="badge" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Badge
        </Link>
        <Link to="breadcrumb" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Breadcrumb
        </Link>
        <Link to="avatar" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Avatar
        </Link>
        <Link to="select" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Select
        </Link>

        <Link to="slider" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Slider
        </Link>

        <Link to="table" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Table
        </Link>
        <Link to="datepicker" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Datepicker
        </Link>
        <Link to="radio" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Radio
        </Link>
        <Link to="dialog" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Dialog
        </Link>
        <Link to="dropdown" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Dropdown
        </Link>
        <Link to="button" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Button
        </Link>
        <Link to="checkbox" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Checkbox
        </Link>
        <Link to="rating" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Rating
        </Link>
        <Link to="tooltip" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Tooltip
        </Link>
        <Link to="alert" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Alert
        </Link>
        <Link to="accordion" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Accordion
        </Link>
        <Link to="chart" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Chart
        </Link>
        <Link to="orgchart" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          OrgChart
        </Link>
        <Link to="tabs" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Tabs
        </Link>
        <Link to="toggle-button" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Toggle Button
        </Link>
        <Link to="phone-input" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Phone Input
        </Link>
        <Link to="tree-view" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Tree View
        </Link>
        <Link to="color-picker" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Color Picker
        </Link>
        <Link to="currency-input" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Currency Input
        </Link>
        <Link to="gantt-chart" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Gantt Chart
        </Link>
        <Link to="upload" className="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100">
          Upload
        </Link>
      </div>
    </TkCard>
  );
}
export default Components;

// apps/vue-app/src/components/Components.vue
<template>
  <TkCard>
    <template #header>
      <h1 class="p-3 text-3xl font-semibold text-slate-500">Components</h1>
    </template>

    <p>Komponent testleri için aşağıdan komponent seçebilirsiniz. Burada olmayan komponentleri benzer düzende ekleyebilirsiniz.</p>

    <div class="grid grid-cols-6 gap-4 mt-4">
      <router-link 
        v-for="component in components" 
        :key="component.path"
        :to="`/components/${component.path}`" 
        class="p-4 border border-indigo-600 rounded-md text-center hover:bg-violet-100"
      >
        {{ component.name }}
      </router-link>
    </div>
  </TkCard>
</template>

<script setup>
import { TkCard } from '@takeoff-ui/vue';

const components = [
  { name: 'Input', path: 'input' },
  { name: 'Stepper', path: 'stepper' },
  { name: 'Toggle', path: 'toggle' },
  { name: 'Divider', path: 'divider' },
  { name: 'Pagination', path: 'pagination' },
  { name: 'Editor', path: 'editor' },
  { name: 'Drawer', path: 'drawer' },
  { name: 'Timeline', path: 'timeline' },
  { name: 'Spinner', path: 'spinner' },
  { name: 'Icon', path: 'icon' },
  { name: 'Chips', path: 'chips' },
  { name: 'Textarea', path: 'textarea' },
  { name: 'Chart', path: 'chart' },
  { name: 'Card', path: 'card' },
  { name: 'Badge', path: 'badge' },
  { name: 'Breadcrumb', path: 'breadcrumb' },
  { name: 'Avatar', path: 'avatar' },
  { name: 'Select', path: 'select' },
  { name: 'Slider', path: 'slider' },
  { name: 'Table', path: 'table' },
  { name: 'Datepicker', path: 'datepicker' },
  { name: 'Radio', path: 'radio' },
  { name: 'Dialog', path: 'dialog' },
  { name: 'Dropdown', path: 'dropdown' },
  { name: 'Button', path: 'button' },
  { name: 'Checkbox', path: 'checkbox' },
  { name: 'Rating', path: 'rating' },
  { name: 'Tooltip', path: 'tooltip' },
  { name: 'Alert', path: 'alert' },
  { name: 'Accordion', path: 'accordion' },
  { name: 'OrgChart', path: 'orgchart' },
  { name: 'Tabs', path: 'tabs' },
  { name: 'Toggle Button', path: 'toggle-button' },
  { name: 'Phone Input', path: 'phone-input' },
  { name: 'Currency Input', path: 'currency-input' },
  { name: 'Tree View', path: 'tree-view' },
  { name: 'Upload', path: 'upload' }
];
</script>
